language: python
python:
  - 2.6
  - 2.7
install:
  - travis_retry pip install coverage coveralls mock zope.testrunner
  - travis_retry pip install -e .
script: coverage run zope-testrunner --test-path=src --auto-color --auto-progress
after_success:
 - coveralls
